name: Deploy to production

on:
  push:
    branches: [ main ]
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./bash-script.sh
         ./bash-script.sh
      shell: bash
